headingLevels:
  - 2
  - 3
  - 4
js: "return {\r\n  link: {\r\n    addTargetToExternalLinks: false,   \r\n    decorators: {\r\n      openInNewTab: {\r\n        attributes: {\r\n          rel: \"noopener noreferrer\",\r\n          target: \"_blank\"\r\n        },\r\n        label: \"Open in a new tab\",\r\n        mode: \"manual\"\r\n      }\r\n    }\r\n  }\r\n}"
name: Builder
toolbar:
  - heading
  - '|'
  - bold
  - underline
  - italic
  - link
  - '|'
  - bulletedList
  - numberedList
  - '|'
  - createEntry
  - '|'
  - removeFormat
