tabs:
  -
    elementCondition: null
    elements:
      -
        dateAdded: '2024-10-09T14:18:02+00:00'
        elementCondition: null
        fieldUid: a8907d08-5c9c-4299-8fcf-b4bc5dfb74b9 # Rarely
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 02ad220d-cc30-491e-b01d-c9ba9266d471
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-10-09T09:28:00+00:00'
        elementCondition: null
        fieldUid: 1d4b9577-b205-4b96-a529-ddf2d98716d9 # Title
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 0658fe90-858d-4f4e-a1ac-bb165e9f98a8
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-10-09T09:28:00+00:00'
        elementCondition: null
        fieldUid: 9a34e9e4-2ce1-4893-80cf-9c5e9e47b225 # Image
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: e9f395af-38e8-4f60-ab69-7d7a8d92ef92
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-10-09T09:28:00+00:00'
        elementCondition: null
        fieldUid: bb561c4c-54b3-40ff-96d3-a135c6abd8a5 # Text
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: c67ddb5c-3179-4c1e-b700-dc958fe30a64
        userCondition: null
        warning: null
        width: 100
      -
        attribute: prices
        dateAdded: '2024-10-01T08:02:43+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\stripe\fieldlayoutelements\PricesField
        uid: 325e1c54-1b05-4d01-8a65-5ec24b0acf61
        userCondition: null
        warning: null
        width: 100
    name: Content
    uid: 77ed3268-2a02-4504-871b-39a2181e4589
    userCondition: null
