tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-12-09T14:37:48+01:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: c2c447b3-3b44-484e-ab22-a95c59ecdfd9
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2024-12-09T14:37:48+01:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 530e1dcd-96b0-4d03-a88e-64c07f6f9dba
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-09T14:37:48+01:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 93dcdd9c-ec4c-42ad-be46-21e0d02a79eb
        userCondition: null
        warning: null
    name: Inhalt
    uid: bf77872d-edc5-425d-ba51-73715ba8ff50
    userCondition: null
